"""empty message

Revision ID: 298586538b89
Revises: 
Create Date: 2020-10-26 21:02:49.196051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298586538b89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(length=64), nullable=True),
    sa.Column('teacher_email', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('hour', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_date'), 'entries', ['date'], unique=False)
    op.create_index(op.f('ix_entries_hour'), 'entries', ['hour'], unique=False)
    op.create_index(op.f('ix_entries_reason'), 'entries', ['reason'], unique=False)
    op.create_index(op.f('ix_entries_student_email'), 'entries', ['student_email'], unique=True)
    op.create_index(op.f('ix_entries_teacher_email'), 'entries', ['teacher_email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_permission'), 'users', ['permission'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_permission'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_entries_teacher_email'), table_name='entries')
    op.drop_index(op.f('ix_entries_student_email'), table_name='entries')
    op.drop_index(op.f('ix_entries_reason'), table_name='entries')
    op.drop_index(op.f('ix_entries_hour'), table_name='entries')
    op.drop_index(op.f('ix_entries_date'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
