"""empty message

Revision ID: 6c21ceec340d
Revises: 298586538b89
Create Date: 2020-10-26 21:11:49.807200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c21ceec340d'
down_revision = '298586538b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entries_student_email', table_name='entries')
    op.create_index(op.f('ix_entries_student_email'), 'entries', ['student_email'], unique=False)
    op.drop_index('ix_entries_teacher_email', table_name='entries')
    op.create_index(op.f('ix_entries_teacher_email'), 'entries', ['teacher_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_teacher_email'), table_name='entries')
    op.create_index('ix_entries_teacher_email', 'entries', ['teacher_email'], unique=1)
    op.drop_index(op.f('ix_entries_student_email'), table_name='entries')
    op.create_index('ix_entries_student_email', 'entries', ['student_email'], unique=1)
    # ### end Alembic commands ###
