"""added DECISION to Entry

Revision ID: ef0f61caea89
Revises: 6c21ceec340d
Create Date: 2020-10-27 15:41:40.624738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0f61caea89'
down_revision = '6c21ceec340d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('decision', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_entries_decision'), 'entries', ['decision'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_decision'), table_name='entries')
    op.drop_column('entries', 'decision')
    # ### end Alembic commands ###
